name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release
              
