name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
      - name: Build Debug
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - name: Run Clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
      - name: Build Release
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release
      - name: Release Unstable
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "unstable"
          prerelease: true
          title: "Development Build"
          files: target/release/ablecpu_launcher
        
              
