name: Manual

on:
  workflow_dispatch:

jobs:
  build_test_release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build Debug
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - name: Run Clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
      - name: Build Release
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release
      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          path: target/release/u_risc_launcher
              
