[package]
name = "ablecpu_vm"
version = "0.9.0"
authors = ["blackfur <64478051+theblackfurguy@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"